protected/models/User.php
<?php

/**
 * This is the model class for table "User".
 *
 * The followings are the available columns in table 'User':
 * @property integer $id
 * @property integer $company_id
 * @property string $date
 * @property string $email
 * @property string $password
 * @property string $name
 * @property string $roles
 * @property string $activity
 * @property integer $active_project_id
 * @property string $location
 * @property string $language
 * @property string $timezone
 * @property double $worktime
 * @property string $workdays
 * @property double $salary
 * @property string $token
 */
class User extends CActiveRecord
{
	public $password2;
	public $avatar;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive User inputs.
		return array(
			array('email', 'required'),
			array('email', 'unique', 'message' => Language::$duplcateEmail),
			array('email', 'length', 'max'=>255),
			array('company_id, active_project_id', 'numerical', 'integerOnly'=>true),
			array('worktime, salary', 'numerical'),
			array('language', 'length', 'max'=>5),
			array('password, password2, name, roles, activity, location, timezone, workdays, avatar', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, company_id, date, email, password, name, roles, activity, active_project_id, location, language, timezone, worktime, workdays, salary, token', 'safe', 'on'=>'search'),
			array('avatar', 'file', 'types'=>'jpg, gif, png', 'safe'=>false, 'allowEmpty'=>true),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'bugs' => array(self::HAS_MANY, 'Bug', 'User_id'),
			'changes' => array(self::HAS_MANY, 'Change', 'User_id'),
			'components' => array(self::HAS_MANY, 'Component', 'User_id'),
			'cutscenes' => array(self::HAS_MANY, 'Cutscene', 'User_id'),
			'dialogs' => array(self::HAS_MANY, 'Dialog', 'User_id'),
			'graphics' => array(self::HAS_MANY, 'Graphic', 'User_id'),
			'levels' => array(self::HAS_MANY, 'Level', 'User_id'),
			'messages' => array(self::HAS_MANY, 'Message', 'User_to_id'),
			'musics' => array(self::HAS_MANY, 'Music', 'User_id'),
			'projects' => array(self::HAS_MANY, 'Project', 'leader_id'),
			'screens' => array(self::HAS_MANY, 'Screen', 'User_id'),
			'sounds' => array(self::HAS_MANY, 'Sound', 'User_id'),
			'timesheets' => array(self::HAS_MANY, 'Timesheet', 'User_id'),
			'company' => array(self::BELONGS_TO, 'Company', 'company_id'),
			'active_project' => array(self::BELONGS_TO, 'Project', 'active_project_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'company_id' => 'Company',
			'date' => 'Date',
			'email' => 'Email',
			'password' => 'Password',
			'name' => 'Name',
			'roles' => 'Roles',
			'activity' => 'Activity',
			'active_project_id' => 'Active Project',
			'location' => 'Location',
			'language' => 'Language',
			'timezone' => 'Timezone',
			'worktime' => 'Worktime',
			'workdays' => 'Workdays',
			'salary' => 'Salary',
			'token' => 'Token',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);

		$criteria->compare('company_id',$this->company_id);

		$criteria->compare('date',$this->date,true);

		$criteria->compare('email',$this->email,true);

		$criteria->compare('password',$this->password,true);

		$criteria->compare('name',$this->name,true);

		$criteria->compare('roles',$this->roles,true);

		$criteria->compare('activity',$this->activity,true);

		$criteria->compare('active_project_id',$this->active_project_id);

		$criteria->compare('location',$this->location,true);

		$criteria->compare('language',$this->language,true);

		$criteria->compare('timezone',$this->timezone,true);

		$criteria->compare('worktime',$this->worktime);

		$criteria->compare('workdays',$this->workdays,true);

		$criteria->compare('salary',$this->salary);

		$criteria->compare('token',$this->salary);

		return new CActiveDataProvider('User', array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','delete'),
				'users'=>array('@'),
			),
			//array('allow', // allow authenticated user to perform 'create' and 'update' actions
			//	'actions'=>array('create','update','delete'),
			//	'users'=>array('@'),
			//),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$model = $this->loadModel();
		if ($model->company_id == Yii::app()->user->company){
			$this->render('view',array(
				'model'=>$model,
			));
		}
		else{
			$this->redirect(Yii::app()->createAbsoluteUrl('/project/index'));
		}
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes = $_POST['User'];

			if (!is_array($model->roles)){
				$model->roles = array();
			}
			if (!is_array($model->workdays)){
				$model->workdays = array();
			}
			$model->company_id = Yii::app()->user->company;
			$model->avatar     = CUploadedFile::getInstance($model,'avatar');
			$model->roles      = implode(',', $model->roles);
			$model->workdays   = implode(',', $model->workdays);

			$token           = md5(uniqid(rand(), true));
			$model->token    = $token;
			$model->password = password_hash(uniqid(rand(), true), PASSWORD_DEFAULT);

			if ($model->validate()){
				$company = Company::model()->findByPK(Yii::app()->user->company);
				$company->month_users += 1;
				$company->update();

				if ($model->name){
					$name = $model->name;
				}
				else{
					$name = $model->email;
				}
				Email::smtp_mail(
					Language::$registerEmailTitle,
					$model->email,
					$name,
					sprintf(Language::$registerEmail, $name, $model->email, $token),
					sprintf(Language::$emailFooter, $model->email, $model->email)
				);

				$model->save();
				if($model->avatar != null){
					$model->avatar->saveAs('files/' . Yii::app()->user->company . '/avatars/' . Yii::app()->user->id . '.png');
				}

				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model = $this->loadModel();
		$model->roles    = explode(',', $model->roles);
		$model->workdays = explode(',', $model->workdays);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			if (!is_array($model->roles)){
				$model->roles = array();
			}
			if (!is_array($model->workdays)){
				$model->workdays = array();
			}
			
			$model->attributes = $_POST['User'];
			$model->avatar     = CUploadedFile::getInstance($model,'avatar');
			$model->roles      = implode(',', $model->roles);
			$model->workdays   = implode(',', $model->workdays);

			$user = user::model()->findByAttributes(array('id'=>$model->id));
			
			if ($model->password == ''){
				$model->password = $user->password;
			}
			else{
				$model->password = password_hash($model->password, PASSWORD_DEFAULT);
			}
			
			$valid = strpos($model->roles, 'admin') !== false;
			
			if (!$valid){
				$users = user::model()->findAllbyAttributes(array(
					'company_id' => $model->company_id
				), ' id != ' . $model->id);
				foreach ($users as $u){
					if (strpos($u->roles, 'admin') !== false){
						$valid = true;
					}
				}
			}

			if ($valid and $model->validate()){
				$model->update();
				if($model->avatar != null){
					$model->avatar->saveAs('files/' . Yii::app()->user->company . '/avatars/' . Yii::app()->user->id . '.png');
				}
				$this->redirect(array('view','id'=>$model->id));
			}
			else{
				$model->roles = explode(',', $model->roles);
				$model->addError('roles', Language::$noAdminError);
			}
		}

		$id = $_GET['id'];
		if ($id == Yii::app()->user->id || in_array('admin', Yii::app()->user->roles)){

			$this->render('update',array(
				'model'=>$model,
			));
		}
		else{
			$this->redirect(Yii::app()->createAbsoluteUrl('/user/index'));
		}
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		$model = $this->loadModel();
		if (isset($_GET['id'])){
			$id = $_GET['id'];
			if ($model->company_id == Yii::app()->user->company && in_array('admin', Yii::app()->user->roles)){
				$user = User::model()->findbyPk($id);
				$user->delete();	
			}
		}
		$this->redirect(Yii::app()->createAbsoluteUrl('/user/index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$users = User::model()->findAllbyAttributes(array('company_id'=>Yii::app()->user->company));

		$this->render('index',array(
			'users'=>$users,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data'),
));
$model->password = '';

$avatar = file_exists($_SERVER['DOCUMENT_ROOT'] . Yii::app()->request->baseUrl . '/files/' . Yii::app()->user->company . '/avatars/' . $model->id . '.png') ? URL . '/files/' . Yii::app()->user->company . '/avatars/' . $model->id . '.png' : URL . '/img/avatar.png';
?>

<div class="box box-success">
<div class="box-header with-border">
	<h3 class="box-title"><?php echo Language::$user; ?></h3>
</div>

<div class="form">
<div class="box-body">
	<a class="btn btn-danger" href="javascript:void(0);" onclick="javascript:introJs().start();" style="position: absolute; right: 10px;"><?php echo Language::$help; ?></a>
	<p class="note"><?php echo Language::$requiredFields; ?></p>

	<?php if ($model->hasErrors() != null){ ?>
		<div class="alert alert-danger">
			<?php echo $form->errorSummary($model); ?>
		</div>
	<?php } ?>
	

	<div class="form-group">
		<label><?php echo Language::$name; ?></label>
		<?php echo $form->textField($model,'name', array('class'=>'form-control', 'placeholder'=>Language::$nameDesc, 'autofocus'=>true)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="form-group <?php if ($model->hasErrors('email') != null) echo 'has-error'; ?>" data-step="1" data-intro="<?php echo Language::$userHelp1; ?>" data-position="left">
		<label><?php echo Language::$email; ?></label>
		<?php echo $form->textField($model,'email', array('class'=>'form-control', 'placeholder'=>Language::$email)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<?php if (!$model->isNewRecord){ ?>
		<div class="form-group <?php if ($model->hasErrors('password') != null) echo 'has-error'; ?>">
			<label><?php echo Language::$password; ?></label>
			<?php echo $form->passwordField($model,'password', array('class'=>'form-control', 'placeholder'=>Language::$password)); ?>
			<?php echo $form->error($model,'password'); ?>
		</div>
	<?php } ?>

	<div class="form-group">
		<label><?php echo Language::$location; ?></label>
		<?php echo $form->textField($model,'location', array('class'=>'form-control', 'placeholder'=>Language::$locationDesc)); ?>
		<?php echo $form->error($model,'location'); ?>
	</div>

	<div class="form-group">
		<label><?php echo Language::$timezone; ?></label>
		<?php echo $form->dropDownList($model,'timezone', Language::$timezones, array('class'=>'form-control')); ?>
		<?php echo $form->error($model,'timezone'); ?>
	</div>

	<div class="form-group">
		<label><?php echo Language::$language; ?></label>
		<?php echo $form->dropDownList($model,'language', Language::$languages, array('class'=>'form-control')); ?>
		<?php echo $form->error($model,'language'); ?>
	</div>

	<?php if (in_array('admin', Yii::app()->user->roles)){ ?>
	<div class="form-group <?php if ($model->hasErrors('roles') != null) echo 'has-error'; ?>" data-step="2" data-intro="<?php echo Language::$userHelp2; ?>" data-position="left">
		<label><?php echo Language::$rolesName; ?></label>
		<?php echo $form->dropDownList($model,'roles', Language::$roles,
			array(
				'class'=>'form-control',
				'multiple'=>'multiple',
			)); ?>
		<?php echo $form->error($model,'roles'); ?>
	</div>
	<?php } ?>

	<div class="form-group">
		<label><?php echo Language::$worktime; ?></label>
		<?php echo $form->textField($model,'worktime', array('class'=>'form-control', 'placeholder'=>Language::$hoursPerDay)); ?>
		<?php echo $form->error($model,'worktime'); ?>
	</div>

	<div class="form-group">
		<label><?php echo Language::$workdays; ?></label>
		<?php echo $form->dropDownList($model,'workdays', Language::$weekdays,
			array(
				'class'=>'form-control',
				'multiple'=>'multiple',
			)); ?>
		<?php echo $form->error($model,'workdays'); ?>
	</div>

	<div class="form-group <?php if ($model->hasErrors('salary') != null) echo 'has-error'; ?>">
		<label><?php echo Language::$salary; ?></label>
		<div class="input-group">
			<div class="input-group-addon">$</div>
			<?php echo $form->textField($model,'salary', array('class'=>'form-control', 'placeholder'=>Language::$perHour)); ?>
		</div>
		<?php echo $form->error($model,'salary'); ?>
	</div>

	<div class="form-group">
		<label><?php echo Language::$avatar; ?></label>
		<?php echo $form->fileField($model, 'avatar'); ?>
		<?php echo $form->error($model,'avatar'); ?>
		<br><img class="img-responsive img-circle" src="<?php echo $avatar; ?>" alt="No Uploaded Image">
	</div>

	<div class="form-group buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? Language::$create : Language::$update, array('class'=>'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div></div></div>

protected/views/user/_menu.php
<?php $this->beginWidget('system.web.widgets.CClipWidget', array('id'=>'globalSidebar')); ?>
<li class="<?php if(Yii::app()->controller->action->id == 'index' || Yii::app()->controller->action->id == 'create') echo 'active' ?> treeview">
  <a href="#">
    <i class="fa fa-users"></i> <span><?php echo Language::$team; ?></span>
    <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
  </a>
  <ul class="treeview-menu">
    <li <?php if(Yii::app()->controller->action->id == 'index') echo 'class="active"'  ?>><a href="<?php echo URL; ?>/user/index"><i class="fa fa-list-ol"></i> <?php echo Language::$userList; ?></a></li>
    
    <?php if (in_array('admin', Yii::app()->user->roles)){?>
      <li <?php if(Yii::app()->controller->action->id == 'create') echo 'class="active"'  ?>><a href="<?php echo URL; ?>/user/create"><i class="fa fa-plus"></i> <?php echo Language::$newUser; ?></a></li>
    <?php } ?>
  </ul>
</li>
<?php $this->endWidget();?>

protected/views/user/_menu2.php
<?php $this->beginWidget('system.web.widgets.CClipWidget', array('id'=>'specificSidebar')); ?>
<li class="active treeview">
  <a href="#">
    <i class="fa fa-user"></i> <span>
      <?php
        echo substr($model->email, 0, 22);
        if (strlen($model->email) > 22){
          echo '...';
        }
        ?>
    </span>
    <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
  </a>
  <ul class="treeview-menu">
    <li <?php if(Yii::app()->controller->action->id == 'view') echo 'class="active"'  ?>><a href="<?php echo URL;?>/user/<?php echo $model->id;?>"><i class="fa fa-info-circle"></i> <?php echo Language::$information; ?></a></li>
    
    <?php if (in_array('admin', Yii::app()->user->roles) || Yii::app()->user->id == $model->id){?>
      <li <?php if(Yii::app()->controller->action->id == 'update') echo 'class="active"'  ?>><a href="<?php echo URL;?>/user/update/<?php echo $model->id;?>"><i class="fa fa-pencil-square-o"></i> <?php echo Language::$update; ?></a></li>

      <?php } if (in_array('admin', Yii::app()->user->roles) and count(User::model()->findAllbyAttributes(array('company_id'=>Yii::app()->user->company))) > 1){?>
      <li><?php echo CHtml::link('<i class="fa fa-ban"></i> ' . Language::$delete, array('user/delete', 'id'=>$model->id), array('onclick'=>'return confirm("' . Language::$confirmDelete . '")')); ?></li>
    <?php } ?>

  </ul>
</li>
<?php $this->endWidget();?>

protected/views/user/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('company_id')); ?>:</b>
	<?php echo CHtml::encode($data->company_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('role')); ?>:</b>
	<?php echo CHtml::encode($data->role); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('worktime')); ?>:</b>
	<?php echo CHtml::encode($data->worktime); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('workdays')); ?>:</b>
	<?php echo CHtml::encode($data->workdays); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('salary')); ?>:</b>
	<?php echo CHtml::encode($data->salary); ?>
	<br />

	*/ ?>

</div>

protected/views/user/create.php
<?php echo $this->renderPartial('_menu'); ?>

<section class="content-header">
  <h1 class="hidden-xs">
    <?php echo Language::$team; ?> <small><?php echo Language::$createMember; ?></small>
  </h1>

  <ol class="breadcrumb">
    <li><a href="<?php echo URL;?>/"><i class="fa fa-dashboard"></i> <?php echo Language::$home; ?></a></li>
    <li><a href="<?php echo URL . '/user';?>"><?php echo Language::$userList; ?></a></li>
    <li class="active"><?php echo Language::$create; ?></li>
  </ol>
</section>

<section class="content">
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</section>

protected/views/user/index.php
<?php echo $this->renderPartial('_menu'); ?>
<section class="content-header">
  <h1 class="hidden-xs"><?php echo Language::$team; ?> <small><?php echo Language::$userList; ?></small></h1>

  <ol class="breadcrumb">
    <li><a href="<?php echo URL;?>/"><i class="fa fa-dashboard"></i> <?php echo Language::$home; ?></a></li>
    <li class="active"><?php echo Language::$userList; ?></li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <?php foreach ($users as $user) {
    $avatar = file_exists($_SERVER['DOCUMENT_ROOT'] . Yii::app()->request->baseUrl . '/files/' . Yii::app()->user->company . '/avatars/' . $user->id . '.png') ? URL . '/files/' . Yii::app()->user->company . '/avatars/' . $user->id . '.png' : URL . '/img/avatar.png'; ?>
    <div class="col-md-4">
      <div class="box box-widget widget-user">
        <a href="<?php echo URL . '/user/' . $user->id ?>">
        <div class="widget-user-header bg-green">
          <h3 class="widget-user-username"><?php echo $user->name ? $user->name: $user->email . '<br/>(' . Language::$languages[$user['language']] . ')'; ?></h3>
        </div>
        <div class="widget-user-image">
          <img class="img-circle" src="<?php echo $avatar; ?>" alt="User Avatar">
        </div>
    	</a>
        <div class="box-footer">
          <div class="col-sm-12">
            <div class="description-block">
              <h5 class="description-header"><?php echo mb_strtoupper(Language::$rolesName); ?></h5>
              <span class="description-text"><?php echo Functions::getRoles($user->roles); ?></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?php } ?>
  </div>
</section>

protected/views/user/update.php
<?php echo $this->renderPartial('_menu'); ?>
<?php echo $this->renderPartial('_menu2', array('model'=>$model)); ?>

<section class="content-header">
  <h1 class="hidden-xs"><?php echo Language::$team; ?> <small><?php echo Language::$updateMember; ?></small></h1>

  <ol class="breadcrumb">
    <li><a href="<?php echo URL;?>/"><i class="fa fa-dashboard"></i> <?php echo Language::$home; ?></a></li>
    <li><a href="<?php echo URL . '/user';?>"><?php echo Language::$userList; ?></a></li>
    <li><a href="<?php echo URL . '/user/' . $model->id;?>"><?php echo $model->name != '' ? $model->name : $model->email; ?></a></li>
    <li><?php echo Language::$update; ?></li>
  </ol>
</section>

<section class="content">
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</section>

protected/views/user/view.php
<?php echo $this->renderPartial('_menu'); ?>
<?php echo $this->renderPartial('_menu2', array('model'=>$model)); ?>
<?php $avatar = file_exists($_SERVER['DOCUMENT_ROOT'] . Yii::app()->request->baseUrl . '/files/' . Yii::app()->user->company . '/avatars/' . $model->id . '.png') ? URL . '/files/' . Yii::app()->user->company . '/avatars/' . $model->id . '.png' : URL . '/img/avatar.png'; ?>

<section class="content-header">
  <h1 class="hidden-xs"><?php echo Language::$team; ?> <small><?php echo Language::$memberDetail; ?></small></h1>

  <ol class="breadcrumb">
    <li><a href="<?php echo URL;?>/"><i class="fa fa-dashboard"></i> <?php echo Language::$home; ?></a></li>
    <li><a href="<?php echo URL . '/user';?>"><?php echo Language::$userList; ?></a></li>
    <li class="active"><?php echo $model->name != '' ? $model->name : $model->email; ?></li>
  </ol>
</section>

<section class="content">
	<div class="box box-success">
    <div class="box-body box-profile">
      <img class="profile-user-img img-responsive img-circle" src="<?php echo $avatar; ?>" alt="User profile picture">

      <h3 class="profile-username text-center"><?php echo $model->name; ?></h3>

      <p class="text-muted text-center"><?php echo Functions::getRoles($model->roles); ?></p>

      <ul class="list-group list-group-unbordered">
        <!--<li class="list-group-item">
          <b><i class="fa fa-user margin-r-5"></i> <?php echo Language::$status; ?></b> <span class="text-muted pull-right"><?php echo $model->activity; ?></span>
        </li>-->
        <li class="list-group-item">
          <b><i class="fa fa-envelope margin-r-5"></i> <?php echo Language::$email; ?></b> <span class="text-muted pull-right"><?php echo $model->email; ?></span>
        </li>
        <li class="list-group-item">
          <b><i class="fa fa-map-marker margin-r-5"></i> <?php echo Language::$location; ?></b> <span class="text-muted pull-right"><?php echo $model->location; ?> <?php echo Language::$timezones[$model->timezone]; ?></span>
        </li>
        <li class="list-group-item">
          <b><i class="fa fa-calendar margin-r-5"></i> <?php echo Language::$workdays; ?></b> <span class="text-muted pull-right"><?php echo Functions::getWeekDays($model->workdays); ?></span>
        </li>
        <li class="list-group-item">
          <b><i class="fa fa-clock-o margin-r-5"></i> <?php echo Language::$worktime; ?></b> <span class="text-muted pull-right"><?php echo $model->worktime; ?> hrs.</span>
        </li>
        <?php if (in_array('admin', Yii::app()->user->roles) || Yii::app()->user->id == $model->id){?>
          <li class="list-group-item">
            <b><i class="fa fa-money margin-r-5"></i> <?php echo Language::$weeklySalary; ?></b> <span class="text-muted pull-right">$<?php echo Functions::getSalary($model->workdays, $model->salary, $model->worktime); ?></span>
          </li>
        <?php } ?>
      </ul>

      <?php if (in_array('admin', Yii::app()->user->roles) || Yii::app()->user->id == $model->id){?>
        <a href="<?php echo URL;?>/user/update/<?php echo $model->id;?>" class="btn btn-primary btn-block"><i class="fa fa-pencil-square-o"></i> <?php echo Language::$edit; ?></a>
      <?php } ?>
      <?php if ($model->id != Yii::app()->user->id){ ?>
        <a href="../messages/<?php echo $model->id; ?>" class="btn btn-success btn-block"><i class="fa fa-comments-o"></i> <b><?php echo Language::$message; ?></b></a>
      <?php } ?>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</section>